### ISSUE TITLE
Implement Global Reference Generator

### ISSUE THREAD

**Issue by MaxBaeten** [tue-robotics/rtt_control_components#8]
Global Reference generator which is a combination of all separate reference generators and read references component in one. Which allows all jointstates to be published on one topic.

## TODO
- [x] add homing input port (obsolete since homing component will get it's own ref gen)
- [x] add function for supervisor to disable bodypart
- [x] add disabled mode where current pos is directly used
- [x] add multiple input ports to controller component
- [x] test new controller component - test multiple inputs and test cleaned up controller
- [x] add reference generator to gripper control component 
- [x] test gripper control component (test with old reference component with one input less)
- [x] fix gripper homing and merge gripper related stuff to refactor branch 
- [x] refactor homing component such that it has it's own ref gen  
- [x] test GlobalReferenceGenerator

**Comment by MaxBaeten** [comment]
Tested and not yet merged to master but were getting there!
